export { default as DashboardHome } from './DashboardHome'
export { default as DashboardMenuPage } from './MenuManager'
export { default as DashboardOrdersPage } from './OrdersPage'
export { default as DashboardPaymentsPage } from './PaymentsPage'
export { default as DashboardAnalyticsPage } from './AnalyticsPage'
export { default as DashboardSurveillancePage } from './SurveillancePage'
export { default as DashboardSettingsPage } from './SettingsPage'
export { default as DashboardHelpPage } from './HelpPage'
