export { default as client } from './client'
export * as authApi from './auth'
export * as restaurantApi from './restaurant'
export * as menuApi from './menu'
export * as ordersApi from './orders'
export * as tablesApi from './tables'
export * as paymentsApi from './payments'
export * as staffApi from './staff'
export * as marketingApi from './marketing'
export * as surveillanceApi from './surveillance'
export * as notificationsApi from './notifications'
export * as aiApi from './ai'
export * as analyticsApi from './analytics'
